# Generated by Django 3.2.7 on 2021-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_device_app_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='app_package',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='element_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='element_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
